# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/james/Documents/static_serial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/james/Documents/static_serial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/Documents/static_serial/CMakeFiles /home/james/Documents/static_serial//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/Documents/static_serial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

demo.o: demo.cpp.o
.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i
.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s
.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.s
.PHONY : demo.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/not_trivially_copyable.o: tests/not_trivially_copyable.cpp.o
.PHONY : tests/not_trivially_copyable.o

# target to build an object file
tests/not_trivially_copyable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/not_trivially_copyable.cpp.o
.PHONY : tests/not_trivially_copyable.cpp.o

tests/not_trivially_copyable.i: tests/not_trivially_copyable.cpp.i
.PHONY : tests/not_trivially_copyable.i

# target to preprocess a source file
tests/not_trivially_copyable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/not_trivially_copyable.cpp.i
.PHONY : tests/not_trivially_copyable.cpp.i

tests/not_trivially_copyable.s: tests/not_trivially_copyable.cpp.s
.PHONY : tests/not_trivially_copyable.s

# target to generate assembly for a file
tests/not_trivially_copyable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/not_trivially_copyable.cpp.s
.PHONY : tests/not_trivially_copyable.cpp.s

tests/test_aggregate.o: tests/test_aggregate.cpp.o
.PHONY : tests/test_aggregate.o

# target to build an object file
tests/test_aggregate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_aggregate.cpp.o
.PHONY : tests/test_aggregate.cpp.o

tests/test_aggregate.i: tests/test_aggregate.cpp.i
.PHONY : tests/test_aggregate.i

# target to preprocess a source file
tests/test_aggregate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_aggregate.cpp.i
.PHONY : tests/test_aggregate.cpp.i

tests/test_aggregate.s: tests/test_aggregate.cpp.s
.PHONY : tests/test_aggregate.s

# target to generate assembly for a file
tests/test_aggregate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_aggregate.cpp.s
.PHONY : tests/test_aggregate.cpp.s

tests/test_annotation.o: tests/test_annotation.cpp.o
.PHONY : tests/test_annotation.o

# target to build an object file
tests/test_annotation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_annotation.cpp.o
.PHONY : tests/test_annotation.cpp.o

tests/test_annotation.i: tests/test_annotation.cpp.i
.PHONY : tests/test_annotation.i

# target to preprocess a source file
tests/test_annotation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_annotation.cpp.i
.PHONY : tests/test_annotation.cpp.i

tests/test_annotation.s: tests/test_annotation.cpp.s
.PHONY : tests/test_annotation.s

# target to generate assembly for a file
tests/test_annotation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_annotation.cpp.s
.PHONY : tests/test_annotation.cpp.s

tests/test_endian.o: tests/test_endian.cpp.o
.PHONY : tests/test_endian.o

# target to build an object file
tests/test_endian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_endian.cpp.o
.PHONY : tests/test_endian.cpp.o

tests/test_endian.i: tests/test_endian.cpp.i
.PHONY : tests/test_endian.i

# target to preprocess a source file
tests/test_endian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_endian.cpp.i
.PHONY : tests/test_endian.cpp.i

tests/test_endian.s: tests/test_endian.cpp.s
.PHONY : tests/test_endian.s

# target to generate assembly for a file
tests/test_endian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_endian.cpp.s
.PHONY : tests/test_endian.cpp.s

tests/test_not_serializable_aggregate.o: tests/test_not_serializable_aggregate.cpp.o
.PHONY : tests/test_not_serializable_aggregate.o

# target to build an object file
tests/test_not_serializable_aggregate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_aggregate.cpp.o
.PHONY : tests/test_not_serializable_aggregate.cpp.o

tests/test_not_serializable_aggregate.i: tests/test_not_serializable_aggregate.cpp.i
.PHONY : tests/test_not_serializable_aggregate.i

# target to preprocess a source file
tests/test_not_serializable_aggregate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_aggregate.cpp.i
.PHONY : tests/test_not_serializable_aggregate.cpp.i

tests/test_not_serializable_aggregate.s: tests/test_not_serializable_aggregate.cpp.s
.PHONY : tests/test_not_serializable_aggregate.s

# target to generate assembly for a file
tests/test_not_serializable_aggregate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_aggregate.cpp.s
.PHONY : tests/test_not_serializable_aggregate.cpp.s

tests/test_not_serializable_scalar.o: tests/test_not_serializable_scalar.cpp.o
.PHONY : tests/test_not_serializable_scalar.o

# target to build an object file
tests/test_not_serializable_scalar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_scalar.cpp.o
.PHONY : tests/test_not_serializable_scalar.cpp.o

tests/test_not_serializable_scalar.i: tests/test_not_serializable_scalar.cpp.i
.PHONY : tests/test_not_serializable_scalar.i

# target to preprocess a source file
tests/test_not_serializable_scalar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_scalar.cpp.i
.PHONY : tests/test_not_serializable_scalar.cpp.i

tests/test_not_serializable_scalar.s: tests/test_not_serializable_scalar.cpp.s
.PHONY : tests/test_not_serializable_scalar.s

# target to generate assembly for a file
tests/test_not_serializable_scalar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_scalar.cpp.s
.PHONY : tests/test_not_serializable_scalar.cpp.s

tests/test_not_serializable_static_container.o: tests/test_not_serializable_static_container.cpp.o
.PHONY : tests/test_not_serializable_static_container.o

# target to build an object file
tests/test_not_serializable_static_container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_static_container.cpp.o
.PHONY : tests/test_not_serializable_static_container.cpp.o

tests/test_not_serializable_static_container.i: tests/test_not_serializable_static_container.cpp.i
.PHONY : tests/test_not_serializable_static_container.i

# target to preprocess a source file
tests/test_not_serializable_static_container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_static_container.cpp.i
.PHONY : tests/test_not_serializable_static_container.cpp.i

tests/test_not_serializable_static_container.s: tests/test_not_serializable_static_container.cpp.s
.PHONY : tests/test_not_serializable_static_container.s

# target to generate assembly for a file
tests/test_not_serializable_static_container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_static_container.cpp.s
.PHONY : tests/test_not_serializable_static_container.cpp.s

tests/test_not_serializable_types.o: tests/test_not_serializable_types.cpp.o
.PHONY : tests/test_not_serializable_types.o

# target to build an object file
tests/test_not_serializable_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_types.cpp.o
.PHONY : tests/test_not_serializable_types.cpp.o

tests/test_not_serializable_types.i: tests/test_not_serializable_types.cpp.i
.PHONY : tests/test_not_serializable_types.i

# target to preprocess a source file
tests/test_not_serializable_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_types.cpp.i
.PHONY : tests/test_not_serializable_types.cpp.i

tests/test_not_serializable_types.s: tests/test_not_serializable_types.cpp.s
.PHONY : tests/test_not_serializable_types.s

# target to generate assembly for a file
tests/test_not_serializable_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_not_serializable_types.cpp.s
.PHONY : tests/test_not_serializable_types.cpp.s

tests/test_padding.o: tests/test_padding.cpp.o
.PHONY : tests/test_padding.o

# target to build an object file
tests/test_padding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_padding.cpp.o
.PHONY : tests/test_padding.cpp.o

tests/test_padding.i: tests/test_padding.cpp.i
.PHONY : tests/test_padding.i

# target to preprocess a source file
tests/test_padding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_padding.cpp.i
.PHONY : tests/test_padding.cpp.i

tests/test_padding.s: tests/test_padding.cpp.s
.PHONY : tests/test_padding.s

# target to generate assembly for a file
tests/test_padding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_padding.cpp.s
.PHONY : tests/test_padding.cpp.s

tests/test_scalar.o: tests/test_scalar.cpp.o
.PHONY : tests/test_scalar.o

# target to build an object file
tests/test_scalar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_scalar.cpp.o
.PHONY : tests/test_scalar.cpp.o

tests/test_scalar.i: tests/test_scalar.cpp.i
.PHONY : tests/test_scalar.i

# target to preprocess a source file
tests/test_scalar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_scalar.cpp.i
.PHONY : tests/test_scalar.cpp.i

tests/test_scalar.s: tests/test_scalar.cpp.s
.PHONY : tests/test_scalar.s

# target to generate assembly for a file
tests/test_scalar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_scalar.cpp.s
.PHONY : tests/test_scalar.cpp.s

tests/test_static_container.o: tests/test_static_container.cpp.o
.PHONY : tests/test_static_container.o

# target to build an object file
tests/test_static_container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_static_container.cpp.o
.PHONY : tests/test_static_container.cpp.o

tests/test_static_container.i: tests/test_static_container.cpp.i
.PHONY : tests/test_static_container.i

# target to preprocess a source file
tests/test_static_container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_static_container.cpp.i
.PHONY : tests/test_static_container.cpp.i

tests/test_static_container.s: tests/test_static_container.cpp.s
.PHONY : tests/test_static_container.s

# target to generate assembly for a file
tests/test_static_container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_static_container.cpp.s
.PHONY : tests/test_static_container.cpp.s

tests/test_variadic_arguments.o: tests/test_variadic_arguments.cpp.o
.PHONY : tests/test_variadic_arguments.o

# target to build an object file
tests/test_variadic_arguments.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_variadic_arguments.cpp.o
.PHONY : tests/test_variadic_arguments.cpp.o

tests/test_variadic_arguments.i: tests/test_variadic_arguments.cpp.i
.PHONY : tests/test_variadic_arguments.i

# target to preprocess a source file
tests/test_variadic_arguments.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_variadic_arguments.cpp.i
.PHONY : tests/test_variadic_arguments.cpp.i

tests/test_variadic_arguments.s: tests/test_variadic_arguments.cpp.s
.PHONY : tests/test_variadic_arguments.s

# target to generate assembly for a file
tests/test_variadic_arguments.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_variadic_arguments.cpp.s
.PHONY : tests/test_variadic_arguments.cpp.s

tests/trivially_copyable.o: tests/trivially_copyable.cpp.o
.PHONY : tests/trivially_copyable.o

# target to build an object file
tests/trivially_copyable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/trivially_copyable.cpp.o
.PHONY : tests/trivially_copyable.cpp.o

tests/trivially_copyable.i: tests/trivially_copyable.cpp.i
.PHONY : tests/trivially_copyable.i

# target to preprocess a source file
tests/trivially_copyable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/trivially_copyable.cpp.i
.PHONY : tests/trivially_copyable.cpp.i

tests/trivially_copyable.s: tests/trivially_copyable.cpp.s
.PHONY : tests/trivially_copyable.s

# target to generate assembly for a file
tests/trivially_copyable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/trivially_copyable.cpp.s
.PHONY : tests/trivially_copyable.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... demo"
	@echo "... tests"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/not_trivially_copyable.o"
	@echo "... tests/not_trivially_copyable.i"
	@echo "... tests/not_trivially_copyable.s"
	@echo "... tests/test_aggregate.o"
	@echo "... tests/test_aggregate.i"
	@echo "... tests/test_aggregate.s"
	@echo "... tests/test_annotation.o"
	@echo "... tests/test_annotation.i"
	@echo "... tests/test_annotation.s"
	@echo "... tests/test_endian.o"
	@echo "... tests/test_endian.i"
	@echo "... tests/test_endian.s"
	@echo "... tests/test_not_serializable_aggregate.o"
	@echo "... tests/test_not_serializable_aggregate.i"
	@echo "... tests/test_not_serializable_aggregate.s"
	@echo "... tests/test_not_serializable_scalar.o"
	@echo "... tests/test_not_serializable_scalar.i"
	@echo "... tests/test_not_serializable_scalar.s"
	@echo "... tests/test_not_serializable_static_container.o"
	@echo "... tests/test_not_serializable_static_container.i"
	@echo "... tests/test_not_serializable_static_container.s"
	@echo "... tests/test_not_serializable_types.o"
	@echo "... tests/test_not_serializable_types.i"
	@echo "... tests/test_not_serializable_types.s"
	@echo "... tests/test_padding.o"
	@echo "... tests/test_padding.i"
	@echo "... tests/test_padding.s"
	@echo "... tests/test_scalar.o"
	@echo "... tests/test_scalar.i"
	@echo "... tests/test_scalar.s"
	@echo "... tests/test_static_container.o"
	@echo "... tests/test_static_container.i"
	@echo "... tests/test_static_container.s"
	@echo "... tests/test_variadic_arguments.o"
	@echo "... tests/test_variadic_arguments.i"
	@echo "... tests/test_variadic_arguments.s"
	@echo "... tests/trivially_copyable.o"
	@echo "... tests/trivially_copyable.i"
	@echo "... tests/trivially_copyable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

